# Generated by Django 5.0.1 on 2024-06-02 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="post_pics"),
        ),
        migrations.AlterField(
            model_name="post",
            name="user_likes",
            field=models.ManyToManyField(
                related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
